mod arithmetic_mean;
mod arth_geo_mean;
mod degree_mean;
mod geometry_mean;
mod what_do_next;
pub use arithmetic_mean::count as arithmetic_mean;
pub use arth_geo_mean::count as arth_geo_mean;
pub use degree_mean::count as degree_mean;
pub use geometry_mean::count as geometry_mean;
pub use what_do_next::what_do as exit_code_algos;
