mod arithmetic_mean;
mod arth_geo_mean;
mod deaviation_mean;
mod degree_mean;
mod geometry_mean;
mod kolmogor_mean;
mod median;
mod moda;
mod modif_arth_geo_mean;
mod trim_mean;
mod vinzor_mean;
mod what_do_next;

pub use arithmetic_mean::count as arithmetic_mean;
pub use arth_geo_mean::count as arth_geo_mean;
pub use deaviation_mean::count as deaviation_mean;
pub use degree_mean::count as degree_mean;
pub use geometry_mean::count as geometry_mean;
pub use kolmogor_mean::count as kolmogor_mean;
pub use median::count as median;
pub use moda::count as moda;
pub use modif_arth_geo_mean::count as modif_arth_geo_mean;
pub use trim_mean::count as trim_mean;
pub use vinzor_mean::count as vinzor_mean;
pub use what_do_next::what_do as exit_code_algos;
