mod arithmetic_mean;
mod arth_geo_mean;
mod deaviation_mean;
mod degree_mean;
mod dispersion;
mod geometry_mean;
mod kolmogor_mean;
mod linear_coeff_deviation;
mod mean_square_dev;
mod median;
mod moda;
mod modif_arth_geo_mean;
mod square_coeff_deviation;
mod trim_mean;
mod vinzor_mean;
mod what_do_next;

pub use arithmetic_mean::print_res as arithmetic_mean;
pub use arth_geo_mean::print_res as arth_geo_mean;
pub use deaviation_mean::print_res as deaviation_mean;
pub use degree_mean::print_res as degree_mean;
pub use dispersion::print_res as dispersion;
pub use geometry_mean::print_res as geometry_mean;
pub use kolmogor_mean::print_res as kolmogor_mean;
pub use linear_coeff_deviation::print_res as linear_coeff_deviation;
pub use mean_square_dev::print_res as mean_square_dev;
pub use median::print_res as median;
pub use moda::print_res as moda;
pub use modif_arth_geo_mean::print_res as modif_arth_geo_mean;
pub use square_coeff_deviation::print_res as square_coeff_deviation;
pub use trim_mean::print_res as trim_mean;
pub use vinzor_mean::print_res as vinzor_mean;
pub use what_do_next::what_do as exit_code_algos;
